### ISSUE TITLE
Potential secutiry vulnerabilities in the shared libraries redlibssh2 depends on. Can you help upgrade to patch versions?

### ISSUE THREAD

**Issue by JoeGardner000** [Red-M/Redlibssh2#1]
Hi, @Red-M, I'd like to report a vulnerability issue in **redlibssh2_2.1.3**.
### Dependency Graph between Python and Shared Libraries
![image](https://user-images.githubusercontent.com/103017573/161988429-3e46fd5a-e8d2-4ed5-8614-5c32a335b789.png)
### Issue Description
As shown in the above dependency graph (Here shows part of the dependency graph, which depends on vulnerable shared libraries), **redlibssh2_2.1.3** directly or transitively depends on ***8*** C libraries (.so). However, I noticed that one C libraries is vulnerable, containing the following CVEs:
`libcrypto-3cc778a5.so.1.1` `libssl-6db5df62.so.1.1`from C project **openssl(version:1.1.0g)** exposed ***7*** vulnerabilities:
[CVE-2019-1543](https://nvd.nist.gov/vuln/detail/CVE-2019-1543), [CVE-2018-0735](https://nvd.nist.gov/vuln/detail/CVE-2018-0735), [CVE-2017-3738](https://nvd.nist.gov/vuln/detail/CVE-2017-3738), [CVE-2020-7043](https://nvd.nist.gov/vuln/detail/CVE-2020-7043), [CVE-2020-7042](https://nvd.nist.gov/vuln/detail/CVE-2020-7042), [CVE-2020-7041](https://nvd.nist.gov/vuln/detail/CVE-2020-7041), [CVE-2019-1552](https://nvd.nist.gov/vuln/detail/CVE-2019-1552) 
### Suggested Vulnerability Patch Versions
***openssl*** has fixed the vulnerabilities in versions ***>=1.1.1l***

Python build tools cannot report vulnerable C libraries, which may induce potential security issues to many downstream Python projects.
As a popular python package (**redlibssh2** has **29,834** downloads per month), could you please upgrade the above shared libraries to their patch versions?

Thanks for your help~
Best regards,
Joe Gardner

**Comment by Red-M** [comment]
The build process for this library uses the latest pypa container (as of build time).

I've read through the listed CVEs, not only do some of them not apply to my library because they're exclusively for openfortivpn but I'd need pypa to update their container to fix these.

The only container that even has a chance of being updated is `quay.io/pypa/manylinux_2_24_x86_64` but this would greatly reduce the number of older linux OSes that could use the library. I may investigate a dynamically linked version instead so that these shared libraries don't need me to update them as they're not baked into the releases (and thus the OS is responsible for updating them and not me).

OSX builds are not affected as these are linked against openssl 3.0.1.

**Comment by Red-M** [comment]
Dynamically linked libssl is a no go as far as pypi is concerned, I think you might want to report this issue to pypa for the containers as these are pretty bad.

**Comment by Red-M** [comment]
I've done more reading and I am allowed to remove openssl based libraries from being statically bundled.

A release is currently being pushed out that removes openssl static objects from both redlibssh and redlibssh2 linux releases, if further issues are raised with OSX builds I will remove those too.
